### PR TITLE
Prevent None prefix in SOAPAction

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by venthur** [comment]
Thank you for your PR! Can you elaborate a bit, what you fixed here?

**Comment by scop** [comment]
Before this patch, for example when calling `get_status`, the code ends up sending `SOAPAction: "Noneget_status"` HTTP header. Doesn't seem to break anything with the current BTS API implementation,  but surely isn't correct either.

**Comment by venthur** [comment]
Thanks for the clarification! Would you mind writing a unittest for this fix?

**Comment by scop** [comment]
Seems that'll require poking at pysimplesoap's internals and anyway more time than I have at the moment, so I think I'll pass right now. Maybe later, but no promises.

**Pull request merged**
